# Generated by Django 5.0.14 on 2026-01-23 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_alter_device_name_device_unique_device_name_per_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_tokens', models.BooleanField(default=False, help_text='Can create/delete API tokens')),
                ('can_create_tokens', models.BooleanField(default=False, help_text='Can create new API tokens')),
                ('view_all_locations', models.BooleanField(default=False, help_text='Can see devices from all locations/countries')),
                ('allowed_locations', models.JSONField(blank=True, default=list, help_text='List of location strings user can see (empty if view_all_locations=True)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_units', models.ManyToManyField(blank=True, help_text='Units/brands this user can see devices from', related_name='authorized_users', to='inventory.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='netwatch_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
