# Generated by Django 5.0.14 on 2026-01-08 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this credential profile', max_length=100, unique=True)),
                ('username', models.CharField(help_text='Windows username (can include domain: DOMAIN\\user or user@domain)', max_length=255)),
                ('password', models.CharField(help_text='Password for the username (encrypted at rest recommended)', max_length=255)),
                ('domain', models.CharField(blank=True, help_text='Optional domain name', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this credential profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credential Profile',
                'verbose_name_plural': 'Credential Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the device', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Static IP address of the device', protocol='IPv4')),
                ('device_type', models.CharField(choices=[('POS', 'POS Terminal'), ('SERVER', 'Server')], default='POS', max_length=10)),
                ('location', models.CharField(blank=True, help_text='Physical location or description', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the device')),
                ('enabled', models.BooleanField(default=True, help_text='Whether monitoring is enabled for this device')),
                ('ping_enabled', models.BooleanField(default=True, help_text='Enable ping checks')),
                ('rdp_check_enabled', models.BooleanField(default=True, help_text='Enable RDP port connectivity check')),
                ('rdp_port', models.PositiveIntegerField(default=3389, help_text='RDP port number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('simphony_check_mode', models.CharField(choices=[('NONE', 'No Simphony Check'), ('WINDOWS_SERVICE', 'Check Windows Service'), ('PROCESS_NAME', 'Check Process Name')], default='NONE', help_text='How to check if Simphony is running', max_length=20)),
                ('simphony_service_name', models.CharField(blank=True, help_text="Windows service name to check (e.g., 'SimphonyService')", max_length=255, null=True)),
                ('simphony_process_name', models.CharField(blank=True, help_text="Process name to check (without .exe, e.g., 'simphony')", max_length=255, null=True)),
                ('check_interval_seconds', models.PositiveIntegerField(default=60, help_text='Interval between checks in seconds', validators=[django.core.validators.MinValueValidator(10)])),
                ('timeout_ms', models.PositiveIntegerField(default=1200, help_text='Timeout for individual checks in milliseconds', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(30000)])),
                ('retries', models.PositiveIntegerField(default=3, help_text='Number of retries on failure', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('failure_threshold', models.PositiveIntegerField(default=3, help_text='Consecutive failures before marking as DOWN', validators=[django.core.validators.MinValueValidator(1)])),
                ('success_threshold', models.PositiveIntegerField(default=1, help_text='Consecutive successes to recover from DOWN', validators=[django.core.validators.MinValueValidator(1)])),
                ('last_status', models.CharField(choices=[('UP', 'Up'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Last known status', max_length=10)),
                ('last_status_change', models.DateTimeField(blank=True, help_text='When the status last changed', null=True)),
                ('last_check_at', models.DateTimeField(blank=True, help_text='When the last check was performed', null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Current count of consecutive failures')),
                ('consecutive_successes', models.PositiveIntegerField(default=0, help_text='Current count of consecutive successes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_profile', models.ForeignKey(blank=True, help_text='Credential profile to use for remote Windows checks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.credentialprofile')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'last_status'], name='inventory_d_enabled_73d350_idx'), models.Index(fields=['device_type'], name='inventory_d_device__82f1fb_idx'), models.Index(fields=['ip_address'], name='inventory_d_ip_addr_2bfa5f_idx')],
            },
        ),
    ]
