# Generated by Django 5.0.14 on 2026-01-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='credential_profile',
        ),
        migrations.RemoveField(
            model_name='device',
            name='rdp_check_enabled',
        ),
        migrations.RemoveField(
            model_name='device',
            name='rdp_port',
        ),
        migrations.RemoveField(
            model_name='device',
            name='simphony_check_mode',
        ),
        migrations.RemoveField(
            model_name='device',
            name='simphony_process_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='simphony_service_name',
        ),
        migrations.DeleteModel(
            name='CredentialProfile',
        ),
    ]
