# Generated by Django 5.0.14 on 2026-01-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_device_credential_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_agent_report',
            field=models.DateTimeField(blank=True, help_text='When the agent last reported status', null=True),
        ),
    ]
