# Generated by Django 5.0.14 on 2026-01-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_device_last_agent_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique authentication token', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this token', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this token was created')),
                ('last_used', models.DateTimeField(blank=True, help_text='When this token was last used', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this token is active')),
                ('device', models.OneToOneField(blank=True, help_text='Device this token is for (optional, can be generic)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to='inventory.device')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
            },
        ),
    ]
