# Generated by Django 5.0.14 on 2026-01-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unit/brand/store name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for this unit')),
                ('location', models.CharField(blank=True, help_text='Optional location/region', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit/brand grouping for this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.unit'),
        ),
    ]
