# Generated by Django 5.0.14 on 2026-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_unit_device_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Friendly name for the device', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_device_name_per_unit'),
        ),
    ]
