# Generated by Django 4.2.10 on 2026-01-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_device_name_device_unique_device_name_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_agent_state',
            field=models.BooleanField(blank=True, help_text='Last known agent state (True=Healthy, False=Unhealthy/None)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_ping_state',
            field=models.BooleanField(blank=True, help_text='Last known ping state (True=UP/OK, False=DOWN/Failed)', null=True),
        ),
    ]
