# Generated by Django 4.2.10 on 2026-01-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_device_last_agent_state_device_last_ping_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_down_services',
            field=models.JSONField(blank=True, default=list, help_text='Last known set of down services/processes for deduplication'),
        ),
    ]
