# Generated by Django 5.0.14 on 2026-01-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('DOWN_ALERT', 'Device Down'), ('UP_ALERT', 'Device Up'), ('DEGRADED_ALERT', 'Service Degraded')], help_text='Type of alert', max_length=20)),
                ('old_status', models.CharField(blank=True, help_text='Previous status', max_length=10)),
                ('new_status', models.CharField(help_text='New status', max_length=10)),
                ('message', models.TextField(help_text='Alert message content')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the alert was sent')),
                ('recipients', models.TextField(help_text='Comma-separated list of recipients')),
                ('success', models.BooleanField(default=True, help_text='Whether the alert was sent successfully')),
                ('error', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('device', models.ForeignKey(help_text='The device this alert is about', on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='inventory.device')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['device', '-sent_at'], name='monitoring__device__199b6e_idx'), models.Index(fields=['-sent_at'], name='monitoring__sent_at_cf2d6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this check was performed')),
                ('ping_ok', models.BooleanField(default=False, help_text='Whether ping was successful')),
                ('ping_ms', models.PositiveIntegerField(blank=True, help_text='Ping response time in milliseconds', null=True)),
                ('rdp_ok', models.BooleanField(default=False, help_text='Whether RDP port was accessible')),
                ('rdp_ms', models.PositiveIntegerField(blank=True, help_text='RDP connection time in milliseconds', null=True)),
                ('simphony_ok', models.BooleanField(blank=True, help_text='Whether Simphony is running (null if not checked)', null=True)),
                ('simphony_status', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('NOT_FOUND', 'Not Found'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Detailed Simphony status', max_length=20)),
                ('overall_status', models.CharField(choices=[('UP', 'Up'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down')], default='DOWN', help_text='Overall device status', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error messages from failed checks')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Number of consecutive failures at the time of this check')),
                ('check_duration_ms', models.PositiveIntegerField(blank=True, help_text='Total duration of the check in milliseconds', null=True)),
                ('device', models.ForeignKey(help_text='The device this check was performed on', on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='inventory.device')),
            ],
            options={
                'verbose_name': 'Check Result',
                'verbose_name_plural': 'Check Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='monitoring__device__881d1b_idx'), models.Index(fields=['overall_status'], name='monitoring__overall_296dcb_idx'), models.Index(fields=['-created_at'], name='monitoring__created_af7548_idx')],
            },
        ),
    ]
