# Generated by Django 5.0.14 on 2026-01-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkresult',
            name='rdp_ms',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='rdp_ok',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='simphony_ok',
        ),
        migrations.RemoveField(
            model_name='checkresult',
            name='simphony_status',
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='overall_status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], default='DOWN', help_text='Overall device status', max_length=10),
        ),
    ]
