# Generated by Django 5.0.14 on 2026-01-08 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_device_last_agent_report'),
        ('monitoring', '0002_remove_checkresult_rdp_ms_remove_checkresult_rdp_ok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the agent sent this report')),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
                ('services_status', models.JSONField(default=dict, help_text='Dictionary of service statuses')),
                ('processes_status', models.JSONField(default=dict, help_text='Dictionary of process statuses')),
                ('agent_healthy', models.BooleanField(default=True, help_text='True if all monitored services/processes are running')),
                ('raw_data', models.JSONField(blank=True, help_text='Full agent report data', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reports', to='inventory.device')),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['device', '-reported_at'], name='monitoring__device__166d47_idx')],
            },
        ),
    ]
