# Generated by Django 5.0.14 on 2026-01-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_apitoken'),
        ('monitoring', '0003_agentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('UP', 'Up'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('new_status', models.CharField(choices=[('UP', 'Up'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the status change occurred')),
                ('reason', models.CharField(blank=True, help_text='Why the status changed (e.g., ping failed, service down)', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inventory.device')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['device', '-changed_at'], name='monitoring__device__c7e554_idx')],
            },
        ),
    ]
