# Generated by Django 5.0.14 on 2026-01-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_statuschangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentreport',
            name='disk_free_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='disk_total_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='disk_used_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='memory_total_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='memory_used_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='process_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentreport',
            name='uptime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
