# Generated by Django 5.1.3 on 2026-01-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_device_name_device_unique_device_name_per_unit'),
        ('monitoring', '0005_agentreport_disk_free_gb_agentreport_disk_total_gb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.BooleanField(help_text='Previous agent health status (True=healthy, False=unhealthy)')),
                ('new_status', models.BooleanField(help_text='New agent health status (True=healthy, False=unhealthy)')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the agent status change occurred')),
                ('reason', models.CharField(blank=True, help_text='Why the agent status changed (e.g., service stopped, agent recovered)', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_status_history', to='inventory.device')),
            ],
            options={
                'verbose_name_plural': 'Agent status histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['device', '-changed_at'], name='monitoring__device__4b311f_idx')],
            },
        ),
    ]
